version: '3.9'

services:
  api:
    ports:
      # Exposes application port.
    - "8000:8000"
    build:
      target: dev
    volumes:
      # Adds current directory as volume.
    - .:/app/src/
    environment:
      # Enables autoreload.
      XRAY_SWAGGER_RELOAD: "True"

  migrator:
    volumes:
    - .:/app/src/

  redis:
    ports:
    - "6379:6379"

  pgadmin:
    image: dpage/pgadmin4:7.5
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
    - pgadmin:/var/lib/pgadmin
    - ./servers.json:/pgadmin4/servers.json
    ports:
    - "${PGADMIN_PORT:-5050}:80"
    restart: unless-stopped
    depends_on:
    - db
    - redis


volumes:
  pgadmin:
