"""Converted models2

Revision ID: eadd32cc6ad6
Revises: db1cc602b44d
Create Date: 2023-07-24 13:22:08.440193

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "eadd32cc6ad6"
down_revision = "db1cc602b44d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "xray_emitter",
        sa.Column("max_scan_range", sa.Integer(), nullable=True, comment="in mm"),
        sa.Column(
            "max_scan_velocity",
            sa.Integer(),
            nullable=True,
            comment="in cm/min",
        ),
        sa.Column(
            "max_voltage",
            sa.DECIMAL(precision=10, scale=4),
            nullable=True,
            comment="in kV",
        ),
        sa.Column(
            "max_current",
            sa.DECIMAL(precision=10, scale=4),
            nullable=True,
            comment="in mA",
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("serial_number", sa.String(length=255), nullable=False),
        sa.Column("device_info_id", sa.Integer(), nullable=True),
        sa.Column("settings", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["device_info_id"],
            ["device_info.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("serial_number"),
    )
    op.create_index(op.f("ix_xray_emitter_id"), "xray_emitter", ["id"], unique=False)
    op.drop_index(
        "ix_peripheraldevicebasemodel_id",
        table_name="peripheraldevicebasemodel",
    )
    op.drop_table("peripheraldevicebasemodel")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "peripheraldevicebasemodel",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "serial_number",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("device_info_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "settings",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["device_info_id"],
            ["device_info.id"],
            name="peripheraldevicebasemodel_device_info_id_fkey",
        ),
        sa.PrimaryKeyConstraint("id", name="peripheraldevicebasemodel_pkey"),
        sa.UniqueConstraint(
            "serial_number",
            name="peripheraldevicebasemodel_serial_number_key",
        ),
    )
    op.create_index(
        "ix_peripheraldevicebasemodel_id",
        "peripheraldevicebasemodel",
        ["id"],
        unique=False,
    )
    op.drop_index(op.f("ix_xray_emitter_id"), table_name="xray_emitter")
    op.drop_table("xray_emitter")
    # ### end Alembic commands ###
